  SELECT * FROM VW_EXTRATO2;
       
        CREATE VIEW VW_EXTRATO AS;
        CREATE VIEW VW_EXTRATO AS;
        SELECT 
			CARTAO.IDCARTAO AS IDCARTAO,
            CARTAO.LIMITE,
            DT_DEBITO AS DATA,
            DESCRICAO,
            PARCELA,
            (DEBITO.VALOR * -1) AS VALOR
		FROM CLIENTE
        LEFT JOIN CARTAO ON 
			CLIENTE.IDCLIENTE = CARTAO.IDCLIENTE
		LEFT JOIN DEBITO ON 
			CARTAO.IDCARTAO = DEBITO.IDCARTAO
		UNION
		SELECT 
			CARTAO.IDCARTAO,
            CARTAO.LIMITE,
            BOLETO.DT_PAGAMENTO,
            'PAGAMENTO DE BOLETO',
            NULL,
            BOLETO.VALOR_PAGO
		FROM CLIENTE
			LEFT JOIN CARTAO ON 
            CLIENTE.IDCLIENTE = CARTAO.IDCLIENTE
			LEFT JOIN BOLETO ON 
            CARTAO.IDCARTAO = BOLETO.IDCARTAO;
        
		SELECT 
			IDCARTAO,
            (LIMITE + IFNULL(SUM(VALOR), 0)) AS SALDO
		FROM 
			VW_EXTRATO2
		GROUP BY
			IDCARTAO,
            LIMITE;
            
            
            
            
            
                     SELECT 
			CARTAO.IDCARTAO,
            CARTAO.LIMITE + (IFNULL(SUM(VALOR_TOTAL), 0 )) - SUM(DEBITO.VALOR) AS SALDO
		FROM 
		SELECT BOLETO.IDCARTAO, BOLETO.IDBOLETO,  BOLETO.VALOR_TOTAL, DT_PAGAMENTO FROM BOLETO WHERE DT_PAGAMENTO IS NOT NULL
		UNION
		SELECT DEBITO.IDCARTAO, DEBITO.IDDEBITO, DEBITO.VALOR, DEBITO.DT_DEBITO FROM DEBITO WHERE DT_DEBITO > DATE_ADD(NOW(), INTERVAL - 1 MONTH)) AS CONSULTA
		RIGHT JOIN CARTAO ON
			CONSULTA.IDCARTAO = CARTAO.IDCARTAO
        GROUP BY CARTAO.IDCARTAO, CARTAO.LIMITE;
        
        
         SELECT * FROM DEBITO;
        SELECT BOLETO.IDCARTAO, BOLETO.IDBOLETO,  BOLETO.VALOR_TOTAL, DT_PAGAMENTO FROM BOLETO WHERE DT_PAGAMENTO IS NULL;
        SELECT DEBITO.IDCARTAO, DEBITO.IDDEBITO, DEBITO.VALOR, DEBITO.DT_DEBITO FROM DEBITO WHERE DT_DEBITO > DATE_ADD(NOW(), INTERVAL - 1 MONTH);
        
            