DROP DATABASE IF EXISTS DBCOTACAO;
CREATE DATABASE DBCOTACAO;
USE DBCOTACAO;

CREATE TABLE COTACAO (
	IDCOTACAO INT NOT NULL AUTO_INCREMENT
    , DTCOTACAO DATE
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY (IDCOTACAO)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY(IDPRODUTO)
);

CREATE TABLE VENDA (
	IDVENDA INT NOT NULL AUTO_INCREMENT
    , IDPRODUTO INT NOT NULL
    , DTVENDA DATE
    , VALOR_REAL NUMERIC(8,2)
    , VALOR_DOLAR NUMERIC(8,2)
    , PRIMARY KEY (IDVENDA)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
    );

INSERT INTO PRODUTO (NOME, VALOR)VALUES('CELULAR', 200);
INSERT INTO PRODUTO (NOME, VALOR)VALUES('TABLET', 350);

INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -5 DAY)), 4.09 - 0.55);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -4 DAY)), 4.09 - 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -3 DAY)), 4.09 - 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -2 DAY)), 4.09 - 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -1 DAY)), 4.09 - 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  0 DAY)), 4.09 - 0.05);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  1 DAY)), 4.09 + 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  2 DAY)), 4.09 + 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  3 DAY)), 4.09 + 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  4 DAY)), 4.09 + 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  5 DAY)), 4.09 + 0.55);


/*
QUESTÃO:
1. SÓ PODE INCLUIR VENDA, SE TIVER COTAÇÃO PARA A DATA DA VENDA
*/
DELIMITER $$
CREATE TRIGGER TR_VENDA_BI BEFORE INSERT ON VENDA FOR EACH ROW
BEGIN
	

    DECLARE vVALOR NUMERIC(8,2);
    
    SELECT VALOR INTO vVALOR FROM PRODUTO WHERE IDPRODUTO = NEW.IDPRODUTO;
    
    SET NEW.VALOR_REAL = vVALOR
	
   
    
    
    IF(NEW.DTVENDA = vDTCOTACAO) THEN
			
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'FOI INSERIDO';
	ELSE 
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NÃO FOI INSERIDO';
	END IF;


END $$
DELIMITER ;
SELECT * FROM VENDA;
SELECT * FROM COTACAO;

DROP TRIGGER TR_VENDA_BI;

DESC VENDA;

DELETE FROM VENDA WHERE IDVENDA = 1;
SELECT * FROM VENDA;
INSERT INTO VENDA VALUES(DEFAULT, 1, (DATE(DATE_ADD(NOW(), INTERVAL + 1 DAY))), 1, 4);

SELECT * FROM COTACAO;
SELECT IDVENDA FROM VENDA WHERE VENDA.IDVENDA = ;

/*

2. QUANDO UM PRODUTO FOR INCLUÍDO OU ALTERADO O VALOR DO PRODUTO 
EM DÓLAR CALCULADO COM BASE NA COTAÇÃO, PARA LOCALIZAR A COTAÇÃO COMPARE A DATA DE VENDA COM A DATA DA COTACAO;
*/


DELIMITER $$
CREATE TRIGGER TR_PRODUTO_AU AFTER UPDATE ON VENDA FOR EACH ROW
BEGIN
	
    SELECT VALOR FROM COTACAO WHERE 
    


END $$
DELIMITER ;





