SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBESTATISTICA;
CREATE DATABASE DBESTATISTICA;
USE DBESTATISTICA;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(45)
	, SEXO CHAR(1)
);

CREATE TABLE ESTATISTICA (	
	HOMEM INT
	, MULHER INT
);

INSERT INTO ESTATISTICA VALUES(0,0);

/* TRIGGER PARA INSERT DE PESSOA */
DROP TRIGGER TR_PESSOA_AI;
DELIMITER $$
CREATE TRIGGER TR_PESSOA_AI AFTER INSERT ON PESSOA FOR EACH ROW
BEGIN

	IF NEW.SEXO = 'M' THEN
    
		UPDATE ESTATISTICA SET HOMEM = HOMEM + 1;
	
    ELSEIF NEW.SEXO = 'F' THEN 
    
		UPDATE ESTATISTICA SET MULHER = MULHER + 1;
        
    ELSE
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "NÃO FOI INSERIDO";
    END IF;

END $$
DELIMITER ;

SHOW TABLES;

/* TRIGGER PARA DELETE DE PESSOA */

DROP TRIGGER TR_PESSOA_AD;
DELIMITER $$
CREATE TRIGGER TR_PESSOA_AD AFTER DELETE ON PESSOA FOR EACH ROW
BEGIN
	
    IF OLD.SEXO = 'M' THEN
		UPDATE ESTATISTICA SET HOMEM = HOMEM -1;
    ELSEIF OLD.SEXO = 'F' THEN
		UPDATE ESTATISTICA SET MULHER = MULHER -1;
    END IF;

END $$
DELIMITER ;

/* TRIGGER PARA UPDATE DE PESSOA */

DROP TRIGGER TR_PESSOA_AU;
DELIMITER $$
CREATE TRIGGER TR_PESSOA_AU AFTER UPDATE ON PESSOA FOR EACH ROW
BEGIN 
	
    IF OLD.SEXO = 'M' AND NEW.SEXO = 'F'THEN
    
		UPDATE ESTATISTICA SET HOMEM = HOMEM -1;
        UPDATE ESTATISTICA SET MULHER = MULHER +1;
        
    ELSEIF OLD.SEXO = 'F' AND NEW.SEXO = 'M' THEN
    
		UPDATE ESTATISTICA SET MULHER = MULHER -1;
        UPDATE ESTATISTICA SET HOMEM = HOMEM +1;
        
    END IF;

END $$
DELIMITER ;

DROP TRIGGER TR_PESSOA_AU;
DROP TABLE ESTATISTICA;
SELECT * FROM PESSOA;
SELECT * FROM ESTATISTICA; 
INSERT INTO PESSOA(NOME, SEXO) VALUES('GUSTAVO', 'M');
DELETE FROM PESSOA WHERE IDPESSOA = 1;
UPDATE PESSOA SET NOME = 'MATEUS' WHERE IDPESSOA = 2;



