CREATE DATABASE DBFUNCIONARIO;

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELRESIDENCIA VARCHAR(11),
    TELCELULAR VARCHAR(11),
    TELRECADO VARCHAR(11)
    

);

