DROP DATABASE DBCARTAOCREDITO;

CREATE DATABASE DBCARTAOCREDITO;

USE DBCARTAOCREDITO;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	CPF CHAR(11) NOT NULL,
	RG VARCHAR(16),
	LOGRADOURO VARCHAR(100),
	NUMERO VARCHAR(10),
	BAIRRO VARCHAR(100),
	CIDADE VARCHAR(100),
	UF CHAR(2),
	COMPLEMENTO VARCHAR(100),
	DT_NASCIMENTO DATE,
	TELEFONE_RESIDENCIAL VARCHAR(15),
	TELEFONE_COMERCIAL VARCHAR(15),
	TELEFONE_RECADO VARCHAR(15)
);
CREATE TABLE CARTAO (
	IDCARTAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDCLIENTE INT NOT NULL,
	NUMERO CHAR(17) NOT NULL,
	DIA_VENCIMENTO INT NOT NULL,
	LIMITE NUMERIC(8,2),
	CONSTRAINT FK_CARTAO_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE DEBITO (
	IDDEBITO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDCARTAO INT NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	PARCELA INT,
	VALOR NUMERIC(8,2) NOT NULL, 
	DT_DEBITO DATETIME,
	CONSTRAINT FK_DEBITO_CARTAO FOREIGN KEY (IDCARTAO) REFERENCES CARTAO(IDCARTAO)
);

CREATE TABLE BOLETO (
	IDBOLETO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDCARTAO INT NOT NULL,
	DT_GERACAO DATE NOT NULL,
	DT_VENCIMENTO DATE NOT NULL,
	VALOR_TOTAL NUMERIC(8,2) NOT NULL, 
	DT_PAGAMENTO DATE,
	VALOR_PAGO NUMERIC(8,2), 
	CONSTRAINT FK_BOLETO_CLIENTE FOREIGN KEY (IDCARTAO) REFERENCES CARTAO(IDCARTAO)
);


CREATE TABLE ITEM_BOLETO (
	IDITEM_BOLETO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDBOLETO INT NOT NULL,
	IDDEBITO INT NOT NULL,
	CONSTRAINT FK_ITEM_BOLETO_BOLETO FOREIGN KEY (IDBOLETO) REFERENCES BOLETO(IDBOLETO),
	CONSTRAINT FK_ITEM_BOLETO_DEBITO FOREIGN KEY (IDDEBITO) REFERENCES DEBITO(IDDEBITO)
);